-- Baseline: the schema previously generated by Hibernate (ddl-auto=update).
-- Existing databases are baselined at this version and skip this script
-- (spring.flyway.baseline-on-migrate); new databases run it.

CREATE TABLE users (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);

CREATE TABLE urls (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    click_count bigint,
    crt_at      timestamp(6) without time zone,
    expiry      timestamp(6) without time zone,
    long_url    text         NOT NULL,
    short_code  varchar(255) NOT NULL,
    user_id     bigint,
    CONSTRAINT uko6lree3tj9uru7b4vo07v6s1n UNIQUE (short_code),
    CONSTRAINT fk31nbxw9e1inas1lmdkwxqv10 FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE analytics_event (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device      varchar(255),
    referrer    varchar(255),
    "timestamp" timestamp(6) without time zone,
    url_id      bigint,
    CONSTRAINT fkl2kx6jmo7b3jhmpvacnpv98vq FOREIGN KEY (url_id) REFERENCES urls (id)
);
